config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "articles#index"
  resources :articles do 
    patch :marked_as_featured, to: 'articles#marked_as_featured'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
    @article = Article.find(params[:id])
  end

  # GET /articles/new
  def new
    @article = current_user.articles.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = current_user.articles.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def marked_as_featured
    outcome = FeatureInteraction.run(user_id: current_user.id, featured_till: params[:featured_till], article_id: params[:article_id])
    respond_to do |format|
      if outcome.valid?
        format.html { redirect_to article_url(params[:article_id]), notice: "Article was successfully updated." }
      else
        format.html { redirect_to article_url(params[:article_id]), notice: outcome.errors.messages }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = current_user.articles.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body, :featured_by_id, :featured_tills)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <div class="row">
    <div class="col-6">
      <p>
        <strong>Title:</strong>
        <%= article.title %>
      </p>

      <p>
        <strong>Body:</strong>
        <%= article.body %>
      </p>
      <% if article.featured_by_id.present? %>
        <p>
          <strong>Featured by:</strong>
          <%= article.featured_by_id %>
        </p>

        <p>
          <strong>Featured till:</strong>
          <%= article.featured_till %>
        </p>
      <% end %>
    </div>
    <div class="col-2">

      <%= form_tag article_marked_as_featured_path(article), method: :patch do %>
        <%= date_field_tag :featured_till,{}, value: article.featured_till,class: "form-control" %><br>
        <%= submit_tag "Feature This Article", class:"btn btn-outline-success mt-1" %>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-6">

    <%= form.label :title, style: "display: block", class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="col-6">

    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <!-- <div>
    <%# form.label :featured_by_id, style: "display: block" %>
    <%# form.number_field :featured_by_id %>
  </div>

  <div>
    <%# form.label :featured_till, style: "display: block" %>
    <%# form.date_field :featured_till %>
  </div>
 -->
  <div class="col-6 mt-2">
    <%= form.submit "Submit", class:"btn btn-success" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article, class: "btn btn-primary" %> |
  <%= link_to "Back to articles", articles_path, class: "btn btn-info" %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="row">
  <div class="col-10">
    <h1>Articles</h1>
  </div>  
  <div class="col-2">
    <%= link_to "New article", new_article_path, class: "btn btn-success" %>
  </div>

</div>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article, class: "btn btn-primary" %>
    </p>
    <hr/>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path, class: "btn btn-info" %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-primary" %> |
  <%= link_to "Back to articles", articles_path, class: "btn btn-info" %>
  <div class="mt-5">
    <%= button_to "Destroy this article", @article, method: :delete, class: "btn btn-danger" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KodesincArticle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar"%>
    <div class="container mt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%=link_to "Kodesinc Articles", root_path, class: "nav-link" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%=link_to "Home", root_path, class: "nav-link" %>
          <!-- <a class="nav-link active" aria-current="page"÷ href="#">Home</a> -->
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= button_to "Log out", destroy_user_session_path, :method => :delete, class:" btn btn-outline-danger" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>